version: '3.8'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    environment:
      - SYNAPSE_SERVER_NAME=localhost
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_ADMIN_USER=admin
      - SYNAPSE_ADMIN_PASSWORD=admin
      - SYNAPSE_DATABASE_TYPE=postgres
      - SYNAPSE_DATABASE_NAME=synapse
      - SYNAPSE_DATABASE_USER=synapse_user
      - SYNAPSE_DATABASE_PASSWORD=admin
      - SYNAPSE_DATABASE_HOST=db
      - SYNAPSE_DATABASE_PORT=5432
    volumes:
      - synapse_data:/data
    ports:
      - "8008:8008"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  synapse_data: {}
  postgres_data: {}
